extends SceneTree
func _init():call_deferred("check")
func check():
 var game=load("res://scripts/game.gd").new()
 var config=ConfigFile.new()
 game.initialize_weapon(config,"2026-09-13")
 assert(game.available_weapons()==["gravecleaver"])
 game.settings_page="game"
 assert(game.option_labels()==["CONTROLS","BACK"])
 for episode in [1,2,3]:
  game.unlock_episode_weapon(episode)
  assert(game.weapon_skin==game.WEAPON_CHOICES[episode])
  assert(game.available_weapons().size()==episode+1)
  game.unlock_episode_weapon(episode)
  assert(game.available_weapons().size()==episode+1)
 config.set_value("game","unlocked_episodes",game.unlocked_episodes)
 config.set_value("game","weapon",game.regular_weapon)
 var restarted=load("res://scripts/game.gd").new()
 restarted.initialize_weapon(config,"2026-09-13")
 assert(restarted.available_weapons()==game.available_weapons() and restarted.weapon_skin=="gatebreaker")
 restarted.unlock_candy_session()
 assert(restarted.weapon_skin=="candy_cane" and restarted.available_weapons().size()==5)
 var fresh=load("res://scripts/game.gd").new()
 fresh.initialize_weapon(config,"2026-09-13")
 assert(not fresh.candy_override and "candy_cane" not in fresh.available_weapons())
 fresh.initialize_weapon(config,"2026-12-25")
 assert(fresh.weapon_skin=="candy_cane" and fresh.holiday=="off")
 config.set_value("game","holiday_seen_date",fresh.holiday_seen_date)
 fresh.initialize_weapon(config,"2026-12-25")
 assert(fresh.weapon_skin=="gatebreaker" and "candy_cane" in fresh.available_weapons())
 fresh.initialize_weapon(config,"2026-12-26")
 assert("candy_cane" not in fresh.available_weapons())
 var legacy=load("res://scripts/game.gd").new()
 legacy.records.finish({"id":"old-win","score":20,"episode":2,"outcome":"won"})
 legacy.initialize_weapon(ConfigFile.new(),"2026-09-13")
 assert(legacy.available_weapons()==["gravecleaver","barrow_star"])
 for node in [game,restarted,fresh,legacy]:node.free()
 assert(ProjectSettings.get_setting("application/boot_splash/show_image")==false)
 print("CAIRN_UNLOCKS_OK: episode rewards, restricted menu, saved progress, legacy wins, Christmas date and session-only candy")
 quit()
