import {screens,duration,drawEffects} from './loops.js';
const $=id=>document.getElementById(id),canvas=document.querySelector('canvas'),g=canvas.getContext('2d');
let selected=0,time=0,running=!matchMedia('(prefers-reduced-motion: reduce)').matches,last=performance.now(),enabled=[true,true];
const images=await Promise.all(screens.map(s=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(Error('Unable to load '+s.file));im.src=s.file}))).catch(e=>{$('description').textContent=e.message;throw e});
screens.forEach((s,i)=>{const b=document.createElement('button');b.innerHTML=`<img src="${s.file}" alt=""><span>0${i+1} / ${s.name}</span>`;b.onclick=()=>select(i);document.querySelector('nav').append(b)});
function select(i){selected=i;time=0;enabled=[true,true];document.querySelectorAll('nav button').forEach((b,j)=>b.setAttribute('aria-pressed',i===j));$('name').textContent=screens[i].name;$('description').textContent=screens[i].mood+' '+screens[i].motion;$('effects').replaceChildren();screens[i].effects.forEach((name,j)=>{const l=document.createElement('label'),c=document.createElement('input');c.type='checkbox';c.checked=true;c.onchange=()=>enabled[j]=c.checked;l.append(c,' '+name);$('effects').append(l)});history.replaceState(null,'','#'+(i+1));draw()}
function draw(){g.drawImage(images[selected],0,0,1280,720);if(!$('still').checked)drawEffects(g,selected,time,enabled);if($('lane').checked){g.fillStyle='#8ccd8b22';g.fillRect(0,720*.68,1280,720*.22);g.strokeStyle='#b1d2a1';g.strokeRect(1,720*.68,1278,720*.22)}if($('bounds').checked){g.strokeStyle='#dec584';g.setLineDash([5,6]);screens[selected].bounds.forEach(([x,y,w,h])=>g.strokeRect(x*1280,y*720,w*1280,h*720));g.setLineDash([])}if($('scale').checked){for(const x of [240,650,1030]){g.save();g.translate(x,585);g.fillStyle='#bfa778';g.strokeStyle='#171e18';g.lineWidth=3;g.beginPath();g.arc(0,-143,12,0,Math.PI*2);g.fill();g.stroke();g.fillRect(-16,-130,32,67);g.fillRect(-14,-63,10,63);g.fillRect(4,-63,10,63);g.restore()}}if($('crop').checked){g.fillStyle='#070a09cc';g.fillRect(0,0,1280,720*.23);g.fillStyle='#ddd5b7';g.font='13px system-ui';g.fillText('Upper band cropped in the native 16:9 arena',18,26)}$('clock').textContent=time.toFixed(2)+' / 8.00s';$('timeline').value=time}
function setRunning(value){running=value;$('play').textContent=running?'Pause':'Play'}
$('play').onclick=()=>setRunning(!running);$('reset').onclick=()=>{time=0;draw()};$('step').onclick=()=>{setRunning(false);time=(time+1/30)%duration;draw()};$('timeline').oninput=e=>{setRunning(false);time=Number(e.target.value);draw()};$('fullscreen').onclick=()=>canvas.requestFullscreen();document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','SELECT','BUTTON'].includes(e.target.tagName)){e.preventDefault();setRunning(!running)}});
function frame(now){if(running){const dt=Math.min(.1,(now-last)/1000)*Number($('speed').value);time=(time+dt)%duration;if($('seam').checked&&time>.35&&time<7.65)time=7.65}last=now;draw();requestAnimationFrame(frame)}
select(Math.max(0,Math.min(3,(Number(location.hash.slice(1))||1)-1)));setRunning(running);requestAnimationFrame(frame);
