export function installComposition(canvas,level,image,editor){
 const bar=document.createElement('div');bar.className='toolbar';bar.innerHTML='<label><input type="checkbox" id="crop">16:9 crop guide</label><label><input type="checkbox" id="actors">Actor scale / occlusion preview</label><label><input type="checkbox" id="foreground" checked>Foreground compositing</label><label><input type="checkbox" id="compare">Show approved biome reference</label><small>Click the scene to move the gold figure’s feet (outside geometry edit mode). Green foot ring = inside walk area.</small>';
 canvas.parentElement.before(bar);const reference=document.createElement('img');reference.src='./citadel-01-v3/base.png';reference.style.cssText='display:none;width:100%;margin:10px 0';reference.alt='Approved World 1 visual reference — aqueduct';canvas.parentElement.after(reference);bar.querySelector('#compare').onchange=e=>reference.style.display=e.target.checked?'block':'none';
 let foot=[.5,.8];canvas.addEventListener('pointerdown',e=>{if(editor.active()||!bar.querySelector('#actors').checked)return;const r=canvas.getBoundingClientRect();foot=[(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height]});
 const inside=(p,poly)=>{let hit=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])hit=!hit}return hit};
 function path(g,poly){g.beginPath();poly.forEach(([x,y],i)=>i?g.lineTo(x*canvas.width,y*canvas.height):g.moveTo(x*canvas.width,y*canvas.height));g.closePath()}
 return {draw(g){if(bar.querySelector('#crop').checked){g.fillStyle='#000a';g.fillRect(0,canvas.height*(1-(level.framing?.bottom_crop||0)),canvas.width,canvas.height*(level.framing?.bottom_crop||0));g.fillRect(0,0,canvas.width,canvas.height*(.23-(level.framing?.bottom_crop||0)));g.strokeStyle='#e9b75f';g.lineWidth=2;g.beginPath();g.moveTo(0,canvas.height*(.23-(level.framing?.bottom_crop||0)));g.lineTo(canvas.width,canvas.height*(.23-(level.framing?.bottom_crop||0)));g.stroke();g.fillStyle='#ffe0a0';g.font='14px sans-serif';g.fillText('Upper scenery cropped at 16:9 with HUD',14,canvas.height*(.23-(level.framing?.bottom_crop||0))-12)}if(!bar.querySelector('#actors').checked)return;
  const actors=[{p:foot,c:'#d1b773'},{p:[.28,.75],c:'#779599'},{p:[.76,.84],c:'#779599'}].sort((a,b)=>a.p[1]-b.p[1]);
  for(const {p,c} of actors){const x=p[0]*canvas.width,y=p[1]*canvas.height,h=canvas.height*.22;g.save();g.translate(x,y);g.fillStyle='#0008';g.beginPath();g.ellipse(0,-2,27,7,0,0,Math.PI*2);g.fill();g.strokeStyle=inside(p,level.walkable.polygon)?'#81c98c':'#ff6262';g.lineWidth=2;g.stroke();g.fillStyle=c;g.strokeStyle=c;g.lineCap='round';g.lineWidth=h*.105;g.beginPath();g.moveTo(-h*.10,0);g.lineTo(-h*.065,-h*.36);g.lineTo(0,-h*.5);g.lineTo(h*.075,-h*.33);g.lineTo(h*.12,0);g.stroke();g.fillRect(-h*.12,-h*.77,h*.24,h*.34);g.beginPath();g.arc(0,-h*.88,h*.085,0,Math.PI*2);g.fill();g.beginPath();g.moveTo(-h*.10,-h*.7);g.lineTo(-h*.23,-h*.41);g.moveTo(h*.10,-h*.7);g.lineTo(h*.25,-h*.49);g.stroke();g.restore()}
  if(bar.querySelector('#foreground').checked)for(const r of level.foreground||[]){g.save();path(g,r.polygon);g.clip();g.drawImage(image,0,0,canvas.width,canvas.height);g.restore()}
 }};
}
