export function installEditor(canvas,level,flow){
 const original=structuredClone(level),key=level.id+'-geometry',undo=[],redo=[];let selected=0,vertex=-1,drag=null,dirty=false;
 const box=document.createElement('section');box.innerHTML=`<div class="toolbar"><label><input id="edit" type="checkbox">Edit geometry</label><select id="shape"></select><button id="undo">Undo</button><button id="redo">Redo</button><button id="delete">Delete vertex</button><button id="addForeground">Add foreground mask</button><button id="removeForeground">Remove foreground mask</button><button id="saveGeo">Export level JSON</button><button id="importGeo">Import JSON</button><button id="resetGeo">Reset to source</button></div><small>Drag vertices. Double-click an edge to insert. Delete removes the selected vertex (minimum 3). Shift-drag moves the whole shape. Ctrl+Z / Ctrl+Y undo/redo. Edits autosave locally; export to commit or request regeneration.</small><div class="toolbar"><span id="geoStatus"></span></div>`;document.querySelector('.stage').before(box);const $=s=>box.querySelector(s);
 function shapes(){let out=[];level.regions.forEach((r,i)=>{out.push({name:r.name+' / area',points:r.polygon});if(r.motion_polygon)out.push({name:r.name+' / flame motion',points:r.motion_polygon})});if(!level.walkable)level.walkable={polygon:[[.025,.699],[.975,.699],[.975,.842],[.025,.842]]};out.push({name:'Walkable foot area',points:level.walkable.polygon});(level.foreground||[]).forEach((r,i)=>out.push({name:r.name||'Foreground '+(i+1),points:r.polygon,foreground:i}));return out}
 function refresh(){const list=shapes();selected=Math.min(selected,list.length-1);$('#shape').replaceChildren(...list.map((s,i)=>{let o=document.createElement('option');o.value=i;o.textContent=s.name;return o}));$('#shape').value=selected;dirty=true}
 function snapshot(){undo.push(JSON.stringify({regions:level.regions,walkable:level.walkable,foreground:level.foreground||[]}));if(undo.length>100)undo.shift();redo.length=0}
 function restore(text){const data=JSON.parse(text);level.regions=data.regions.map(({exclusions,...region},i)=>({...region,...(original.regions[i].animation?{animation:original.regions[i].animation}:{})}));level.walkable=data.walkable;level.foreground=data.foreground??structuredClone(original.foreground||[]);vertex=-1;refresh();persist()}
 function persist(){try{localStorage.setItem(key,JSON.stringify({regions:level.regions,walkable:level.walkable,foreground:level.foreground||[]}));$('#geoStatus').textContent='Geometry saved locally'}catch{$('#geoStatus').textContent='Local save failed - export JSON'}dirty=true}
 try{const saved=localStorage.getItem(key);if(saved)restore(saved)}catch{}refresh();
 $('#addForeground').onclick=()=>{snapshot();(level.foreground??=[]).push({name:'Foreground '+((level.foreground||[]).length+1),polygon:[[.02,.85],[.10,.85],[.10,.98],[.02,.98]]});refresh();selected=shapes().length-1;$('#shape').value=selected;$('#edit').checked=true;persist()};
 $('#removeForeground').onclick=()=>{const i=shapes()[selected].foreground;if(i===undefined)return;snapshot();level.foreground.splice(i,1);selected=0;vertex=-1;refresh();persist()};
 const active=()=>$('#edit').checked;$('#shape').onchange=()=>{selected=Number($('#shape').value);vertex=-1};
 function point(e){const r=canvas.getBoundingClientRect();return [(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height]}
 const distance=(a,b)=>Math.hypot((a[0]-b[0])*canvas.width,(a[1]-b[1])*canvas.height);
 canvas.style.touchAction='none';canvas.addEventListener('pointerdown',e=>{if(!active())return;const p=point(e),pts=shapes()[selected].points;vertex=pts.findIndex(v=>distance(v,p)<13);if(vertex<0&&!e.shiftKey)return;snapshot();drag={start:p,points:structuredClone(pts),whole:e.shiftKey};canvas.setPointerCapture(e.pointerId);e.preventDefault()});
 canvas.addEventListener('pointermove',e=>{if(!drag)return;const p=point(e),pts=shapes()[selected].points;if(drag.whole){let dx=p[0]-drag.start[0],dy=p[1]-drag.start[1];dx=Math.max(-Math.min(...drag.points.map(v=>v[0])),Math.min(1-Math.max(...drag.points.map(v=>v[0])),dx));dy=Math.max(-Math.min(...drag.points.map(v=>v[1])),Math.min(1-Math.max(...drag.points.map(v=>v[1])),dy));pts.forEach((v,i)=>{v[0]=drag.points[i][0]+dx;v[1]=drag.points[i][1]+dy})}else{pts[vertex]=p.map(v=>Math.max(0,Math.min(1,v)))}dirty=true});
 canvas.addEventListener('pointerup',()=>{if(drag){drag=null;persist()}});canvas.addEventListener('pointercancel',()=>{drag=null;persist()});
 canvas.addEventListener('dblclick',e=>{if(!active())return;const p=point(e),pts=shapes()[selected].points;let best={d:Infinity};pts.forEach((a,i)=>{let b=pts[(i+1)%pts.length],dx=(b[0]-a[0])*canvas.width,dy=(b[1]-a[1])*canvas.height,t=Math.max(0,Math.min(1,((p[0]-a[0])*canvas.width*dx+(p[1]-a[1])*canvas.height*dy)/(dx*dx+dy*dy||1))),q=[a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t],d=distance(p,q);if(d<best.d)best={d,q,i}});if(best.d<24){snapshot();pts.splice(best.i+1,0,best.q);vertex=best.i+1;persist()}});
 function remove(){let pts=shapes()[selected].points;if(vertex>=0&&pts.length>3){snapshot();pts.splice(vertex,1);vertex=-1;persist()}}$('#delete').onclick=remove;
 function history(from,to){if(!from.length)return;to.push(JSON.stringify({regions:level.regions,walkable:level.walkable,foreground:level.foreground||[]}));restore(from.pop())}$('#undo').onclick=()=>history(undo,redo);$('#redo').onclick=()=>history(redo,undo);
 window.addEventListener('keydown',e=>{if(!active()||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();remove()}if(e.ctrlKey&&['z','y'].includes(e.key.toLowerCase())){e.preventDefault();e.key.toLowerCase()==='z'?history(undo,redo):history(redo,undo)}});
 function download(name,content,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 $('#saveGeo').onclick=()=>download(level.id+'-edited.json',JSON.stringify(level,null,2));
 $('#importGeo').onclick=()=>{const input=document.createElement('input');input.type='file';input.accept='.json';input.onchange=async()=>{try{const data=JSON.parse(await input.files[0].text());if(!Array.isArray(data.regions)||data.regions.length!==level.regions.length)throw Error('Region count must match current screen');const polygons=data.regions.flatMap(r=>[r.polygon,...(r.motion_polygon?[r.motion_polygon]:[])]);if(data.walkable)polygons.push(data.walkable.polygon);if(data.foreground&&!Array.isArray(data.foreground))throw Error("Invalid foreground list");polygons.push(...(data.foreground||[]).map(r=>r.polygon));if(polygons.some(p=>!Array.isArray(p)||p.length<3||p.some(v=>!Array.isArray(v)||v.length!==2||v.some(n=>!Number.isFinite(n)||n<0||n>1))))throw Error('Invalid normalized polygon');snapshot();restore(JSON.stringify(data))}catch(e){$('#geoStatus').textContent='Import failed: '+e.message}};input.click()};
 $('#resetGeo').onclick=()=>{snapshot();restore(JSON.stringify(original))};
 return {active,draw(ctx){if(dirty){flow?.updateRegions(level.regions);dirty=false}if(!active())return;const list=shapes();list.forEach((s,i)=>{ctx.beginPath();s.points.forEach(([x,y],n)=>n?ctx.lineTo(x*canvas.width,y*canvas.height):ctx.moveTo(x*canvas.width,y*canvas.height));ctx.closePath();ctx.strokeStyle=i===selected?'#fff':'#71968d';ctx.lineWidth=i===selected?2:1;ctx.stroke();if(i===selected)s.points.forEach(([x,y],n)=>{ctx.beginPath();ctx.arc(x*canvas.width,y*canvas.height,n===vertex?6:4,0,Math.PI*2);ctx.fillStyle=n===vertex?'#ffb24c':'#fff';ctx.fill()})})}};
}
