import fs from 'node:fs';
import {spawnSync} from 'node:child_process';
import {createCanvas,loadImage,GlobalFonts} from '@napi-rs/canvas';
const dir='E:/Cairn-build-tools/trailer';
const c=createCanvas(1920,1080),g=c.getContext('2d');
g.drawImage(await loadImage('studies/backgrounds/citadel-04-v1/base.png'),0,0,1920,1080);
g.fillStyle='rgba(0,0,0,.73)';g.fillRect(0,0,1920,1080);
const logo=await loadImage('godot/art/cairn-logo.png');const width=1370,height=width*logo.height/logo.width;
g.drawImage(logo,(1920-width)/2,440-height/2,width,height);
GlobalFonts.registerFromPath('asset-sources/fonts/cinzel.ttf','Cinzel');g.font='32px Cinzel';g.fillStyle='#c6b69b';g.textAlign='center';g.fillText('STEEL.  BLOOD.  THUNDER.',960,785);
fs.writeFileSync(dir+'/endcard.png',c.toBuffer('image/png'));
const filter=`[0:v]trim=start=0.1:end=26,setpts=PTS-STARTPTS,tpad=stop_mode=clone:stop_duration=0.1,scale=1920:1080:flags=lanczos,setsar=1,fade=t=out:st=25.84:d=0.16[v0];
[1:v]fps=30,trim=duration=4,zoompan=z='1.03-0.03*min(on/24,1)':x='iw/2-iw/zoom/2':y='ih/2-ih/zoom/2':d=1:s=1920x1080:fps=30,setsar=1,fade=t=in:st=0:d=0.1,fade=t=out:st=3.55:d=0.45[v1];
[v0][v1]concat=n=2:v=1:a=0[v];
[0:a]atrim=start=0.1:end=26,asetpts=PTS-STARTPTS,apad=whole_dur=30,volume=1.15[sfx];
[2:a]atrim=start=4:end=34,asetpts=PTS-STARTPTS,volume='if(between(t,25.65,26),0.06,0.65)':eval=frame,afade=t=in:d=0.12,afade=t=out:st=28.6:d=1.4[music];
[3:a]atrim=duration=3,asetpts=PTS-STARTPTS,volume=0.75,adelay=26000|26000[hit];
[sfx][music][hit]amix=inputs=3:duration=longest:normalize=0,atrim=duration=30,alimiter=limit=0.92:level=false,loudnorm=I=-16:TP=-1.2:LRA=9[a]`;
fs.writeFileSync(dir+'/edit-filter.txt',filter);
const args=['-y','-hide_banner','-loglevel','warning','-i',dir+'/master.avi','-loop','1','-i',dir+'/endcard.png','-i','godot/audio_options/music_game-2.ogg','-i','godot/audio/slam_boom.ogg','-filter_complex_script',dir+'/edit-filter.txt','-map','[v]','-map','[a]','-t','30','-r','30','-c:v','libx264','-crf','18','-preset','slow','-pix_fmt','yuv420p','-c:a','aac','-b:a','256k','-ar','48000','-movflags','+faststart',dir+'/cairn-first-cut.mp4'];
const result=spawnSync('ffmpeg',args,{stdio:'inherit',windowsHide:true});if(result.status!==0)process.exit(result.status||1);
console.log(dir+'/cairn-first-cut.mp4');
