import fs from 'node:fs';
import path from 'node:path';
export function incrementBuild(root){
 const file=path.join(root,'version.json');
 const info=JSON.parse(fs.readFileSync(file,'utf8'));
 if(!/^\d+\.\d+\.\d+(?:-[a-zA-Z0-9.-]+)?$/.test(info.version)||!Number.isSafeInteger(info.build)||info.build<0||info.build>=Number.MAX_SAFE_INTEGER)throw Error('Invalid version.json: expected version and nonnegative integer build');
 info.build++;
 fs.writeFileSync(file,JSON.stringify(info,null,2)+'\n');
 fs.writeFileSync(path.join(root,'godot/scripts/build_info.gd'),'# Generated by the build pipeline from version.json.\nextends RefCounted\nconst VERSION='+JSON.stringify(info.version)+'\nconst BUILD='+info.build+'\n');
 console.log(`Cairn v${info.version} · build ${info.build}`);
 return info;
}
